# Generated by Django 2.2.1 on 2019-05-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('telefones', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='costumer',
            name='tipo',
            field=models.TextField(choices=[('empresa', 'Empresa'), ('pessoa', 'Pessoa')], default='Empresa'),
        ),
    ]
